application: python3wos
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: python3wos.py
  secure: optional

skip_files:
- .*\.cache.*

